cuda: True
ngpu: 1
gpu_id: '0'
data_dir: /home/luka/homework/std/va2/VA_Project/Train     # Your dataset path
video_flist: '/home/luka/homework/std/va2/VA_Project/proj_demo/filelists/Video_Name_List.txt'
audio_flist: '/home/luka/homework/std/va2/VA_Project/proj_demo/filelists/Audio_Name_List.txt'
workers: 4
batchSize: 30
checkpoint_folder: ./checkpoints_test
init_model: './checkpoints/model_1.pth'
topk: 5
